unit EntitiesU;

interface

uses
  MVCFramework.Serializer.Commons,
  MVCFramework.ActiveRecord,
  MVCFramework.Nullables;

type
  TEntityBase = class abstract(TMVCActiveRecord)
  protected
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    fID: Integer;
  public
    property ID: Integer read fID write fID;
  end;

  TPersonEntityBase = class abstract(TEntityBase)
  private
    [MVCTableField('dob')]
    fDateOfBirth: TDate;
  public
    property DateOfBirth: TDate read fDateOfBirth write fDateOfBirth;
  end;

  [MVCNameCase(ncLowerCase)]
  [MVCTable('customers')]
  TCustomer = class(TPersonEntityBase)
  private
    [MVCTableField('last_name')]
    fLastName: string;
    [MVCTableField('first_name')]
    fFirstName: string;
    [MVCTableField('note')]
    fNote: NullableString;
  public
    property FirstName: string read fFirstName write fFirstName;
    property LastName: string read fLastName write fLastName;
    property Note: NullableString read fNote write fNote;
  end;

implementation

end.
